/**
 * Offline icon-existence verification using the pre-built dictionary
 * generated from @iconify/json.
 *
 * The dictionary is NOT injected into LLM prompts.  It is used by:
 * - `buildSlideAssetMetadata()` to verify/correct icon IDs before writing
 *   slide-assets.json
 * - `enforceIconCollection()` to confirm the target stem actually exists
 *   in the selected collection
 *
 * The dict file is generated by `scripts/generate-icon-dict.mjs`.
 */

import iconDict from './iconify-dict.json' with { type: 'json' }
import type { IconifyCollectionId } from './iconify'

type IconDict = Record<string, string[]>
const dict: IconDict = iconDict as IconDict

// Build Set indexes lazily for O(1) lookups
const _indexCache = new Map<string, Set<string>>()

function getIndex(prefix: string): Set<string> {
  let index = _indexCache.get(prefix)
  if (!index) {
    const names = dict[prefix]
    index = names ? new Set(names) : new Set()
    _indexCache.set(prefix, index)
  }
  return index
}

/**
 * Check whether a full Iconify ID (e.g. `fluent:database-24-regular`) exists
 * in the offline dictionary.
 */
export function iconExists(fullId: string): boolean {
  if (!fullId || !fullId.includes(':')) return false
  const [prefix, ...rest] = fullId.split(':')
  const stem = rest.join(':')
  return getIndex(prefix).has(stem)
}

/**
 * Check whether a stem (e.g. `database-24-regular`) exists within a specific
 * collection prefix.
 */
export function iconExistsInCollection(stem: string, prefix: string): boolean {
  return getIndex(prefix).has(stem)
}

/** Return all supported collection prefixes present in the dictionary. */
export function getSupportedPrefixes(): string[] {
  return Object.keys(dict)
}
